/**
 * @file options-trading.model.ts
 * @description Strongly-typed domain models for options market data, order lifecycle,
 * multileg credit spreads, and broker accounting within the Balaboost platform.
 */

/**
 * Standard OCC (Options Clearing Corporation) symbology component breakdown.
 * Example OCC Symbol: 'SPXW261102P07425000'
 */
export interface ParsedOccOption {
  /** The underlying ticker root (e.g. 'SPX', 'SPXW', 'SPY') */
  rootSymbol: string;
  /** Expiration year in 4-digit format (e.g. 2026) */
  expirationYear: number;
  /** Expiration month 1-12 */
  expirationMonth: number;
  /** Expiration day 1-31 */
  expirationDay: number;
  /** Option contract type: 'Call' | 'Put' */
  optionType: 'Call' | 'Put';
  /** Exact strike price in USD (e.g. 7425.00) */
  strikePrice: number;
  /** Human-readable formatted string (e.g. 'SPXW $7,425 Put · Exp: Nov 2, 2026') */
  formattedDescription: string;
}

/**
 * Represents a single component leg of a multileg options order or position.
 */
export interface TradierOrderLeg {
  id?: number;
  type?: string;
  symbol?: string;
  /** Standard 21-character OCC option symbol (e.g. 'SPXW261102P07425000') */
  option_symbol: string;
  /** Order side: 'sell_to_open' | 'buy_to_open' | 'buy_to_close' | 'sell_to_close' */
  side: 'sell_to_open' | 'buy_to_open' | 'buy_to_close' | 'sell_to_close' | 'buy' | 'sell' | string;
  /** Number of contracts for this specific leg */
  quantity: number;
  status?: string;
  duration?: string;
  avg_fill_price?: number;
  exec_quantity?: number;
  last_fill_price?: number;
  last_fill_quantity?: number;
  remaining_quantity?: number;
  create_date?: string;
  transaction_date?: string;
}

/**
 * Represents an order placed with or retrieved from the Tradier broker.
 */
export interface TradierOrder {
  /** Broker order identifier */
  id: number;
  /** Order type: 'market' | 'limit' | 'stop' | 'credit' | 'debit' */
  type: string;
  /** Underlying ticker symbol (e.g. 'SPX') */
  symbol: string;
  /** Order side for single-leg equity orders */
  side?: string;
  /** Total contracts or leg quantity sum */
  quantity: number;
  /** Executed limit price per share or net credit/debit */
  price?: number;
  /** Average fill price reported by Tradier */
  avg_fill_price?: number;
  /** Executed quantity filled */
  exec_quantity?: number;
  /** Time in force: 'day' | 'gtc' */
  duration: 'day' | 'gtc' | string;
  /** Order status reported by broker */
  status:
    | 'pending'
    | 'open'
    | 'submitted'
    | 'accepted'
    | 'queued'
    | 'held'
    | 'partially_filled'
    | 'filled'
    | 'canceled'
    | 'rejected'
    | 'expired'
    | string;
  /** Time when the order was submitted */
  create_date: string;
  transaction_date?: string;
  /** Order class: 'equity' | 'option' | 'multileg' | 'combo' */
  class: 'equity' | 'option' | 'multileg' | 'combo' | string;
  /** Number of distinct legs (e.g. 2 for vertical spreads) */
  num_legs?: number;
  /** Spread strategy name if identified (e.g. 'credit_spread', 'Bull Put Spread') */
  strategy?: string;
  /** Component option legs for multileg orders */
  leg?: TradierOrderLeg[];
  /** Detailed rejection description from the exchange/broker if rejected */
  reason_description?: string;
  tag?: string;
}

/**
 * Tradier brokerage account cash and margin balances.
 */
export interface TradierAccountBalance {
  total_cash?: number;
  total_equity?: number;
  market_value?: number;
  option_buying_power?: number;
  stock_buying_power?: number;
  margin_buying_power?: number;
  pending_cash?: number;
  open_pnl?: number;
  close_pnl?: number;
  totalValue?: number;
  cashAvailable?: number;
  buyingPower?: number;
  optionBuyingPower?: number;
  closePnL?: number;
  openPnL?: number;
}

/**
 * Individual option leg details returned by the Pricing Engine recommendation.
 */
export interface TradeRecommendationLeg {
  /** OCC Option Symbol */
  symbol: string;
  /** Strike price in points/dollars */
  strike: number;
  /** Current highest bid */
  bid: number;
  /** Current lowest ask */
  ask: number;
  /** Mid price = (bid + ask) / 2 */
  mid: string;
  /** Option delta (-1.0 to 1.0) */
  delta?: number;
}

/**
 * Algorithmic trade preview generated by the Options Pricing Engine.
 */
export interface TradeRecommendation {
  /** Action: 'Trade' when conditions align, 'Halt' when waiting or conditions invalid */
  action: 'Trade' | 'Halt';
  /** Explanation if action is 'Halt' */
  reason?: string;
  /** Underlying symbol (e.g. 'SPX') */
  symbol?: string;
  /** Identified strategy: 'Bull Put Spread' | 'Bear Call Spread' */
  strategy?: 'Bull Put Spread' | 'Bear Call Spread';
  /** Selected expiration date (YYYY-MM-DD) */
  expiration?: string;
  /** Current underlying spot price */
  underlyingPrice?: number;
  /** Short leg to sell for premium */
  shortLeg?: TradeRecommendationLeg;
  /** Protective long wing to buy */
  longLeg?: TradeRecommendationLeg;
  /** Fair-value net credit before aggressiveness adjustment */
  netCreditMid?: string;
  /** Immediate natural market credit (Short Bid - Long Ask) */
  naturalCredit?: string;
  /** Exchange tick-size rounded limit price recommendation */
  recommendedLimitPrice?: string;
  /** Active execution mode */
  executionMode?: string;
  /** Execution aggressiveness profile based on market tags */
  aggressiveness?: string;
  /** Strike distance in points between short and long legs */
  spreadWidth?: number;
  /** The maximum spread width ceiling applied by the Hybrid Delta Cap */
  maxSpreadWidthCap?: number;
  /** Whether the hybrid cap clamped the wing closer than pure 10Δ */
  capApplied?: boolean;
  /** Technical market tags evaluated during analysis */
  tagsUsed?: string[];
}

/**
 * Operating schedule configuration for the automated trading window.
 */
export interface TradingHoursConfig {
  /** Whether to enforce the trading window */
  enabled: boolean;
  /** Window opening time in Eastern Time (HH:MM, e.g. '10:00') */
  startTime: string;
  /** Window closing time in Eastern Time (HH:MM, e.g. '15:00') */
  endTime: string;
  /** Allow weekend execution for testing */
  allowWeekend: boolean;
  /** Sandbox testing bypass to execute outside window */
  allowOutsideHoursPaper: boolean;
}

/**
 * Live evaluation status of the trading hours filter.
 */
export interface TradingHoursStatus {
  isWithinWindow: boolean;
  canExecuteTrade: boolean;
  marketStatus?: 'open' | 'closed' | 'pre_market' | 'after_hours';
  windowStatus?: 'active' | 'paused' | 'disabled';
  currentEasternTime?: string;
  currentEasternDate?: string;
  formattedClock?: string;
  currentTimeET?: string;
  currentDayET?: string;
  isWeekend?: boolean;
  reason: string;
  config: TradingHoursConfig;
}

/**
 * Lightweight Charts candlestick bar data point.
 */
export interface CandleBarData {
  time: number; // Unix timestamp in seconds
  open: number;
  high: number;
  low: number;
  close: number;
}

/**
 * Live OHLC inspection values for the hovered or latest candlestick.
 */
export interface ActiveBarValues {
  time: string;
  open: number;
  high: number;
  low: number;
  close: number;
  change: number;
  changePct: number;
  ema8?: number;
  ema21?: number;
}
